// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BF2Statistics.Web.Bf2Stats
{
    using System.Collections.Generic;
    using System.Text;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class HomePage : HomePageBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
                    "/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xh" +
                    "tml\" class=\"inner\">\r\n<head>\r\n\t<title>");
            
            #line 7 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Title));
            
            #line default
            #line hidden
            this.Write("</title>\r\n\r\n\t<link rel=\"icon\" href=\"");
            
            #line 9 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/favicon.ico\" type=\"image/x-icon\">\r\n\t<link rel=\"shortcut icon\" href=\"");
            
            #line 10 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/favicon.ico\" type=\"image/x-icon\">\r\n\t<link rel=\"stylesheet\" type=\"text/css\" media" +
                    "=\"screen\" href=\"");
            
            #line 11 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/scripts/two-tiers.css\">\r\n\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" " +
                    "href=\"");
            
            #line 12 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/scripts/nt.css\">\r\n\t<link rel=\"stylesheet\" type=\"text/css\" media=\"print\" href=\"");
            
            #line 13 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/scripts/print.css\">\r\n\t<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href" +
                    "=\"");
            
            #line 14 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/scripts/default.css\">\r\n\r\n\t<script type=\"text/javascript\">/* no frames */ if(top." +
                    "location != self.location) top.location.replace(self.location);</script>\r\n\t<scri" +
                    "pt type=\"text/javascript\" src=\"");
            
            #line 17 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/scripts/nt2.js\"></script>\r\n\t<script type=\"text/javascript\" src=\"");
            
            #line 18 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/scripts/show.js\"></script>\r\n</head>\r\n<body class=\"inner\">\r\n<div id=\"page-1\">\r\n\t<" +
                    "div id=\"page-2\">\r\n\t\t<h1 id=\"page-title\">");
            
            #line 23 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Title));
            
            #line default
            #line hidden
            this.Write("</h1>\r\n\t\t<div id=\"page-3\">\r\n\t\t\t<div id=\"content\"><div id=\"content-id\">\r\n\t\t\t\t<!--\r" +
                    "\n\t\t\t\t<ul id=\"stats-nav\">\r\n\t\t\t\t\t<li class=\"current\"><a href=\"");
            
            #line 28 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("\">Home</a></li>\r\n\t\t\t\t\t<li><a href=\"");
            
            #line 29 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/search\">Search Stats</a></li>\r\n\t\t\t\t\t<li><a href=\"");
            
            #line 30 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/rankings\">Current Ranking</a></li>\r\n\t\t\t\t\t<li><a href=\"");
            
            #line 31 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/myleaderboard\">My Leaderboard</a></li>\r\n\t\t\t\t</ul>\r\n\t\t\t\t-->\r\n\t\t\t\t<div id=\"content" +
                    "\">\r\n\t\t\t\t\t<div id=\"content-id\"><!-- template header end == begin content below --" +
                    ">\r\n\t\t\t\t\t\t<center>\r\n\t\t\t\t\t\t\t<h2>Top ");
            
            #line 37 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Players.Count));
            
            #line default
            #line hidden
            this.Write(@" Players</h2>
							<table cellspacing=""0"" cellpadding=""0"" border=""0"" style=""width: auto;"" class=""stat"">
							<tbody>
								<tr>
									<th>#</th>
									<th>Nick</th>
									<th>Global Score</th>
									<th>Country</th>
									<th>Time</th>
								</tr>
								");
            
            #line 47 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
 
                                for(int i = 0; i < this.Players.Count; i++)
								{	
									
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t\t\t<td>");
            
            #line 52 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i + 1));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
            
            #line 54 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/images/ranks/icon/rank_");
            
            #line 54 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Players[i]["rank"]));
            
            #line default
            #line hidden
            this.Write(".gif\">&nbsp;\r\n\t\t\t\t\t\t\t\t\t\t\t<a href=\"");
            
            #line 55 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/player?pid=");
            
            #line 55 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Players[i]["id"]));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 55 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Players[i]["name"]));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t<td>");
            
            #line 57 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Players[i]["score"]));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
            
            #line 59 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/images/flags/");
            
            #line 59 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Players[i]["country"]));
            
            #line default
            #line hidden
            this.Write(".png\" height=\"12\" width=\"16\">\r\n\t\t\t\t\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t\t\t\t\t<td>");
            
            #line 61 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TimeSpan.FromSeconds(Int32.Parse(this.Players[i]["time"].ToString()))));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t\t\t");
            
            #line 63 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t</tbody>\r\n\t\t\t\t\t\t\t</table>\r\n\t\t\t\t\t\t</center>\r\n\t\t\t\t\t\t<a id=\"secondhome\" href=" +
                    "\"");
            
            #line 67 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write(@"""> </a>
						<!-- end content == footer below -->
						<hr class=""clear"">
					</div>
				</div> <!-- content-id --><!-- content -->
			</div></div>
		</div>	<!-- Page 3 -->
		<div id=""footer"">Generated using the <a href='http://bf2statistics.com'>BF2Statistics Control Center</a></div>
		<ul id=""navitems"">
			<li><a href=""");
            
            #line 76 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("\">Home</a></li>\r\n\t\t\t<li><a href=\"");
            
            #line 77 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/myleaderboard\">My Leader Board</a></li>\r\n\t\t\t<li><a href=\"");
            
            #line 78 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/rankings\">Rankings</a></li>\r\n\t\t\t<!--\r\n\t\t    <li><a href=\"");
            
            #line 80 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/ubar\">UBAR</a></li>\r\n\t\t    <li><a href=\"http://wiki.bf2s.com/\">Wiki</a></li>\r\n  " +
                    "          -->\r\n\t\t</ul>\r\n\t\t<form action=\"");
            
            #line 84 "D:\Programming\C#\Projects\BF2Statistics\BF2Statistics\Web\Bf2Stats\Pages\HomePage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Root));
            
            #line default
            #line hidden
            this.Write("/search\" method=\"post\" id=\"getstats\">\r\n\t\t\t<label for=\"pid\">Get Stats</label>\r\n\t\t\t" +
                    "<input type=\"text\" name=\"searchvalue\" id=\"pid\" value=\"\" />\r\n\t\t\t<input type=\"subm" +
                    "it\" class=\"btn\" value=\"Go\" />\r\n\t\t</form>\r\n\t</div><!-- page 2 -->\r\n</div>\r\n</body" +
                    ">\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class HomePageBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
